### ISSUE TITLE
No puedo hacer que entre en con contraseña

### ISSUE THREAD

**Issue by M0E-lnx** [PyAr/lalita#14]
Cuando un canal esta protegido por una contraseña (+k), donde se pone esta para que lalita ingrese al canal?

**Comment by facundobatista** [comment]
Hay soporte para servers con clave y también ponerle clave al hacer login; pero lo de ponerle clave al canal todavía no está soportado.

Hay que hacerlo.

**Comment by M0E-lnx** [comment]
+1
